name: .NET Core

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          cache: true

      - name: Install dependencies
        run: dotnet restore mobipark.sln
        working-directory: ./backend

      - name: Build
        run: dotnet build mobipark.sln --configuration Release --no-restore
        working-directory: ./backend

      - name: Publish build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./backend/bin

  tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          cache: true

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./backend/bin

      - name: Run tests
        run: dotnet test mobipark.sln --no-restore --verbosity normal
        working-directory: ./backend
